# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c28e0eebedfc1d291123c8e456b20c6b0283bbf7f6f6fc1ad2062886cb30bd5f4ed38a12958455e176e74a51ef24b3ccfaade8f541bf01171a9441a9d5e8aebe

test:
  secret_key_base: 97f95d1b13e7c8ee8ff15cfe0094122354245b081c4f9e35d8e4a7055b2920ca044cabc7ab9746ef47083df825dfa3a7969232b5ca77e1564920cb27084d8c51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
